---
dependencies:
  - role: "geerlingguy.pip"
    become: yes
    vars:
      pip_install_packages:
        - name: docker

  - role: "geerlingguy.docker"
    become: yes
    vars:
      docker_users:
        - "{{ ansible_ssh_user }}"
