---
- name: Ensure the conf dir exists
  file:
    path: "{{ base_data_path }}/conf"
    state: directory
  notify: restart concord_console

- name: Create the configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  loop:
  - { src: "console.j2.conf", dest: "{{ base_data_path }}/conf/console.conf" }
  - { src: "cfg.j2.js", dest: "{{ base_data_path }}/conf/cfg.js" }
  notify: restart concord_console

- name: Create the console container
  become: true
  docker_container:
    name: console
    image: "walmartlabs/concord-console:latest"
    pull: true
    state: started
    network_mode: host
    volumes:
    - "{{ base_data_path }}/conf/console.conf:/opt/concord/console/nginx/app.conf:ro"
    - "{{ base_data_path }}/conf/cfg.js:/opt/concord/console/dist/cfg.js:ro"
    restart_policy: unless-stopped
  register: docker_container_concord_console
